name: Python Code Standards Check

on:
  pull_request:
    branches: [ main ]  # Adjust if your default branch has a different name

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify your required Python version

      - name: Install Dependencies
        run: |
          # Install dependencies from requirements.txt if it exists
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          # Install flake8 and nbqa to lint both Python files and notebooks
          pip install flake8 nbqa

      - name: Run flake8 Lint Check on Python Files
        run: flake8 .

      - name: Run nbqa flake8 on Notebooks
        run: nbqa flake8 .
